class Vendor {
  String? number,
      id,
      userNo,
      userId,
      card,
      name,
      mobile,
      email,
      address,
      type,
      paidOrFree,
      discount,
      minimumAmount,
      logo,
      banner,
      category,
      subCategory,
      description;

  Vendor(
      {this.number,
      this.id,
      this.userNo,
      this.userId,
      this.card,
      this.name,
      this.mobile,
      this.email,
      this.address,
      this.type,
      this.paidOrFree,
      this.discount,
      this.minimumAmount,
      this.logo,
      this.banner,
      this.category,
      this.subCategory,
      this.description});

  factory Vendor.fromJson(Map<String, dynamic> json) => Vendor(
        number: json['sequenceNo'],
        id: json['topVendorId'],
        userNo: json['userNo'],
        userId: json['userId'],
        card: json['cardNo'],
        name: json['name'],
        mobile: json['mobileNo'],
        email: json['emailId'],
        address: json['address'],
        type: json['userType'],
        paidOrFree: json['paidOrFree'],
        discount: json['discountPercent'],
        minimumAmount: json['minimumAmount'],
        logo: json['vendorLogo'],
        banner: json['vendorBanner'],
        category: json['category'],
        subCategory: json['subCategory'],
        description: json['description'],
      );
}
